# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True)),
                ('iata', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
