# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20170425_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
