# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroute',
            name='actualdeparturetime',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='aircrafttype',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='destinationCity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='destinationName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='estimatedarrivaltime',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='filed_departuretime',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='ident',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='originCity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enroute',
            name='originName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
